spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URL}:${DB_PORT:5432}/${DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

app:
  reports-directory-name: reports
  roles-directory-name: roles
  excerpts-directory-name: excerpts

redash:
  url: ${REDASH_URL}
  api-key: ${REDASH_API_KEY}